
services:
  main-app:
    build:
      context: .

    container_name: main-app

    ports:
      - 8000:8000

    volumes:
      - ./src:/src

    command: > 
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"

    depends_on:
      - db

    environment:
      DB_HOST: db
      DB_NAME: db_postgres
      DB_USER: postgres
      DB_PASS: postgres

  db:
    image: postgres:15-alpine3.16
    container_name: db
    restart: always

    environment:
      POSTGRES_DB: db_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

