
services:
  main-app:
    build:
      context: .

    container_name: main-app

    ports:
      - 8000:8000

    volumes:
      - ./src:/src

    command: > 
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"